export const GET_FILTER_USERS_REQUEST = "GET_FILTER_USERS_REQUEST";
export const GET_FILTER_USERS_SUCCESS = "GET_FILTER_USERS_SUCCESS";
export const GET_FILTER_USERS_FAILURE = "GET_FILTER_USERS_FAILURE";
